### ISSUE TITLE
Readable Uptime text

### ISSUE THREAD

**Issue by damooooooooooh** [tim-hellhake/systeminfo-adapter#8]
Seconds value will get large and meaningless value.  Would be good to have the time adjust  to a more meaningful text like hours, days, weeks etc

**Comment by tim-hellhake** [comment]
I would love to improve it, but the problem is I can't change the property unit once the device is registered.
The only option I currently see is to change the type of the property to `string` and let the addon format the time string.
This comes with a price, though.
In order to show the value of the property in the device view, I have to use a `LevelProperty`, which means only `number` values are allowed.
This would no longer work with a `string` property.

**Comment by damooooooooooh** [comment]
Ah ok and that could also screw up any rules set on that property too.  Ok understand.

**Comment by damooooooooooh** [comment]
Closed

**Comment by tim-hellhake** [comment]
@damooooooooooh 
I found a way to update the unit of the property dynamically.
There are two uptime properties now.
The new one automatically scales to a reasonable time unit and is responsible for the content of the device icon.
The original uptime property is meant to be used in rules as you need a fixed unit to make sense of the values.
